name: BlocklyNukkit
main: com.blocklynukkit.loader.Loader
version: "1.2.9.5"
author: 超神的冰凉
api: ["1.0.11"]
description: BN插件加载器(BlocklyNukkit_Plugin_Loader)
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - EconomyAPI
  - ScoreboardPlugin
  - FakeInventories
  - Tips
  - PyBN
  - GameAPI
  - miraiBN
  - WebassemblyBN

#声明：blocklynukkit使用的红石音乐引擎转制自bukkit版本