name: BlocklyNukkit
main: dls.icesight.blocklynukkit.Loader
version: "1.1.9"
author: BlocklyNukkit开发组（超神的冰凉发起）
authors:
  - 超神的冰凉
  - 企鹅队长
api: ["1.0.8"]
description: BN插件加载器
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - EconomyAPI
  - ScoreboardPlugin