name: BlocklyNukkit
main: dls.icesight.blocklynukkit.Loader
version: "1.1.9"
author: BlocklyNukkit开发组-超神的冰凉发起(BlocklyNukkit_Developers)
authors:
  - 超神的冰凉
  - 企鹅队长
api: ["1.0.8"]
description: BN插件加载器(BlocklyNukkit_JS_Plugin_Loader)
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - EconomyAPI
  - ScoreboardPlugin

#声明：blocklynukkit使用的红石音乐引擎转制自bukkit版本